source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Leaderboard' do
	pod 'SlackKit', :git => 'https://github.com/pvzig/SlackKit.git', :branch => 'swift2.3'
end

# Set SWIFT_VERSION to 2.3 manually
post_install do |installer|
  installer.pods_project.targets.each do |target|
  	target.build_configurations.each do |config|
    	config.build_settings['SWIFT_VERSION'] = '2.3'
  	end
  end
end